/** The 7 macro-regions for WHERE markets */
export const REGIONS = [
  "north",
  "haifa",
  "sharon",
  "dan",
  "jerusalem",
  "south",
  "gaza_envelope",
] as const;

export type Region = (typeof REGIONS)[number];

export const REGION_LABELS: Record<Region, { he: string; en: string }> = {
  north: { he: "צפון", en: "North" },
  haifa: { he: "חיפה", en: "Haifa" },
  sharon: { he: "שרון", en: "Sharon" },
  dan: { he: "דן", en: "Dan" },
  jerusalem: { he: "ירושלים", en: "Jerusalem" },
  south: { he: "דרום", en: "South" },
  gaza_envelope: { he: "עוטף עזה", en: "Gaza Envelope" },
};

/**
 * Comprehensive mapping of Hebrew city/area names from Pikud HaOref / Tzofar alerts to macro-regions.
 * ~1,050 entries covering all official Pikud HaOref zones.
 */
const CITY_REGION_MAP: Record<string, Region> = {
  // === NORTH - קו העימות (Lebanon Border) ===
  "אביבים": "north",
  "אבירים": "north",
  "אבן מנחם": "north",
  "אדמית": "north",
  "אזור תעשייה אכזיב מילואות": "north",
  "אזור תעשייה רמת דלתון": "north",
  "אילון": "north",
  "אלקוש": "north",
  "בית הלל": "north",
  "בית ספר שדה מירון": "north",
  "בן עמי": "north",
  "בצת": "north",
  "ברעם": "north",
  "ג'ש - גוש חלב": "north",
  "גונן": "north",
  "גורן": "north",
  "גורנות הגליל": "north",
  "געתון": "north",
  "גשר הזיו": "north",
  "דוב''ב": "north",
  "דובב": "north",
  "דישון": "north",
  "דלתון": "north",
  "קיבוץ דן": "north",
  "דן": "north",
  "דפנה": "north",
  "הגושרים": "north",
  "הילה": "north",
  "זרעית": "north",
  "חוסן": "north",
  "חורפיש": "north",
  "חניתה": "north",
  "יחיעם": "north",
  "יערה": "north",
  "יפתח": "north",
  "יראון": "north",
  "כברי": "north",
  "כפר בלום": "north",
  "כפר גלעדי": "north",
  "כפר ורדים": "north",
  "כפר יובל": "north",
  "כפר סאלד": "north",
  "כרם בן זמרה": "north",
  "להבות הבשן": "north",
  "לימן": "north",
  "מרכז אזורי מבואות חרמון": "north",
  "מטולה": "north",
  "מלכיה": "north",
  "מנות": "north",
  "מנרה": "north",
  "מעונה": "north",
  "מעיין ברוך": "north",
  "מעיליא": "north",
  "מעלות תרשיחא": "north",
  "מעלות-תרשיחא": "north",
  "מצובה": "north",
  "מרגליות": "north",
  "משגב עם": "north",
  "מתת": "north",
  "נאות מרדכי": "north",
  "נהריה": "north",
  "נווה זיו": "north",
  "נטועה": "north",
  "סאסא": "north",
  "סער": "north",
  "עבדון": "north",
  "עברון": "north",
  "ע'ג'ר": "north",
  "גג'ר": "north",
  "עין יעקב": "north",
  "עלמה": "north",
  "עמיר": "north",
  "ערב אל עראמשה": "north",
  "פסוטה": "north",
  "פקיעין": "north",
  "צבעון": "north",
  "צוריאל": "north",
  "קריית שמונה": "north",
  "ראש הנקרה": "north",
  "ריחאנייה": "north",
  "רמות נפתלי": "north",
  "שאר ישוב": "north",
  "שדה נחמיה": "north",
  "שומרה": "north",
  "שלומי": "north",
  "שמיר": "north",
  "שניר": "north",
  "שתולה": "north",
  "תל חי": "north",
  "בירנית": "north",
  "סנהדריה": "north",

  // === NORTH - גליל עליון (Upper Galilee) ===
  "אבו סנאן": "north",
  "אור הגנוז": "north",
  "אזור תעשייה בר-לב": "north",
  "אזור תעשייה חצור הגלילית": "north",
  "אזור תעשייה כרמיאל": "north",
  "אזור תעשייה צ.ח.ר": "north",
  "אזור תעשייה שער נעמן": "north",
  "אחיהוד": "north",
  "איילת השחר": "north",
  "אליפלט": "north",
  "אמירים": "north",
  "אמנון": "north",
  "אפק": "north",
  "אשרת": "north",
  "בוסתן הגליל": "north",
  "ביריה": "north",
  "בית ג'אן": "north",
  "בית העמק": "north",
  "בענה": "north",
  "בר יוחאי": "north",
  "ג'דידה מכר": "north",
  "ג'וליס": "north",
  "גדות": "north",
  "גיתה": "north",
  "דיר אל-אסד": "north",
  "הר-חלוץ": "north",
  "חולתה": "north",
  "חצור הגלילית": "north",
  "חרשים": "north",
  "טובא זנגריה": "north",
  "טל-אל": "north",
  "ינוח-ג'ת": "north",
  "יסוד המעלה": "north",
  "יסעור": "north",
  "ירכא": "north",
  "כורזים ורד הגליל": "north",
  "כחל": "north",
  "כיסרא סמיע": "north",
  "כישור": "north",
  "כליל": "north",
  "כמון": "north",
  "כפר הנשיא": "north",
  "כפר יסיף": "north",
  "כפר מסריק": "north",
  "כפר שמאי": "north",
  "כרכום": "north",
  "כרמיאל": "north",
  "לבון": "north",
  "לוחמי הגטאות": "north",
  "לפידות": "north",
  "מג'דל כרום": "north",
  "מרכז אזורי מרום גליל": "north",
  "מזרעה": "north",
  "מחניים": "north",
  "מירון": "north",
  "מכמנים": "north",
  "מנחת מחניים": "north",
  "משמר הירדן": "north",
  "נחף": "north",
  "נס עמים": "north",
  "נתיב השיירה": "north",
  "סאג'ור": "north",
  "ספסופה - כפר חושן": "north",
  "עין אל אסד": "north",
  "עין המפרץ": "north",
  "עין כמונים": "north",
  "עכו": "north",
  "עכו - אזור תעשייה": "north",
  "עמוקה": "north",
  "עמיעד": "north",
  "עמקה": "north",
  "פלך": "north",
  "פרוד": "north",
  "צורית גילון": "north",
  "צפת": "north",
  "קדיתא": "north",
  "קדרים": "north",
  "ראמה": "north",
  "ראש פינה": "north",
  "רגבה": "north",
  "שבי ציון": "north",
  "שדה אליעזר": "north",
  "שומרת": "north",
  "שזור": "north",
  "שייח' דנון": "north",
  "שפר": "north",
  "תובל": "north",

  // === NORTH - מרכז הגליל (Central Galilee) ===
  "אבטליון": "north",
  "אזור תעשייה תרדיון": "north",
  "אעבלין": "north",
  "אשבל": "north",
  "אשחר": "north",
  "בועיינה-נוג'ידאת": "north",
  "ביר אלמכסור": "north",
  "בית סוהר צלמון": "north",
  "בית רימון": "north",
  "דיר חנא": "north",
  "דמיידה": "north",
  "הררית יחד": "north",
  "חוסנייה": "north",
  "חזון": "north",
  "חנתון": "north",
  "טורעאן": "north",
  "טמרה": "north",
  "טפחות": "north",
  "יובלים": "north",
  "יודפת": "north",
  "יעד": "north",
  "כאבול": "north",
  "כאוכב אבו אלהיג'א": "north",
  "כלנית": "north",
  "כפר חנניה": "north",
  "כפר מנדא": "north",
  "לוטם וחמדון": "north",
  "מורן": "north",
  "מורשת": "north",
  "מנוף": "north",
  "מסד": "north",
  "מע'אר": "north",
  "מעלה צביה": "north",
  "מצפה אבי''ב": "north",
  "מצפה נטופה": "north",
  "מרכז אזורי משגב": "north",
  "סכנין": "north",
  "סח'נין": "north",
  "סלמה": "north",
  "עוזייר": "north",
  "עילבון": "north",
  "עינבר": "north",
  "עצמון - שגב": "north",
  "עראבה": "north",
  "ערב אל-נעים": "north",
  "קורנית": "north",
  "ראס אל-עין": "north",
  "רומאנה": "north",
  "רומת אל הייב": "north",
  "רקפת": "north",
  "שורשים": "north",
  "שכניה": "north",
  "שעב": "north",
  "שפרעם": "north",

  // === NORTH - גליל תחתון (Lower Galilee) ===
  "בית ירח": "north",
  "אלומות": "north",
  "אפיקים": "north",
  "ארבל": "north",
  "בית זרע": "north",
  "גבעת אבני": "north",
  "גינוסר": "north",
  "דגניה א": "north",
  "דגניה ב": "north",
  "הודיות": "north",
  "הזורעים": "north",
  "ואדי אל חמאם": "north",
  "חוקוק": "north",
  "טבריה": "north",
  "יבנאל": "north",
  "כינרת מושבה": "north",
  "כינרת קבוצה": "north",
  "כפר זיתים": "north",
  "כפר חיטים": "north",
  "כפר כמא": "north",
  "כפר נהר הירדן": "north",
  "לביא": "north",
  "לבנים": "north",
  "מגדל": "north",
  "מצפה": "north",
  "פוריה כפר עבודה": "north",
  "פוריה נווה עובד": "north",
  "פוריה עילית": "north",
  "רביד": "north",
  "שדה אילן": "north",
  "שרונה": "north",

  // === NORTH - גולן (Golan Heights) ===
  "אודם": "north",
  "אורטל": "north",
  "אל רום": "north",
  "בוקעתא": "north",
  "בוקעאתא": "north",
  "מג'דל שמס": "north",
  "מסעדה": "north",
  "מרום גולן": "north",
  "נווה אטי''ב": "north",
  "נמרוד": "north",
  "עין זיוון": "north",
  "עין קנייא": "north",
  "קלע": "north",
  "שעל": "north",
  "אבני איתן": "north",
  "אלוני הבשן": "north",
  "אלי עד": "north",
  "אלמגור": "north",
  "אניעם": "north",
  "אפיק": "north",
  "אשדות יעקב איחוד": "north",
  "אשדות יעקב מאוחד": "north",
  "בני יהודה וגבעת יואב": "north",
  "גשור": "north",
  "האון": "north",
  "חד נס": "north",
  "חמת גדר": "north",
  "חספין": "north",
  "יונתן": "north",
  "כנף": "north",
  "כפר חרוב": "north",
  "מבוא חמה": "north",
  "מיצר": "north",
  "מסדה": "north",
  "מעגן": "north",
  "מעלה גמלא": "north",
  "נאות גולן": "north",
  "נוב": "north",
  "נטור": "north",
  "עין גב": "north",
  "קדמת צבי": "north",
  "קצרין": "north",
  "קצרין - אזור תעשייה": "north",
  "קשת": "north",
  "רמות": "north",
  "רמת מגשימים": "north",
  "שער הגולן": "north",
  "תל קציר": "north",

  // === NORTH - העמקים (Jezreel Valley) ===
  "אום אל-גנם": "north",
  "אורנים": "north",
  "אחוזת ברק": "north",
  "אילניה": "north",
  "אכסאל": "north",
  "אלון הגליל": "north",
  "אלוני אבא": "north",
  "אלונים": "north",
  "בית לחם הגלילית": "north",
  "בית קשת": "north",
  "בית שערים": "north",
  "בלפוריה": "north",
  "בסמת טבעון": "north",
  "קבוצת גבע": "north",
  "גבעת אלה": "north",
  "גבת": "north",
  "גדעונה": "north",
  "גזית": "north",
  "גן נר": "north",
  "גניגר": "north",
  "דבוריה": "north",
  "דברת": "north",
  "דחי": "north",
  "הושעיה": "north",
  "היוגב": "north",
  "הסוללים": "north",
  "הרדוף": "north",
  "זרזיר": "north",
  "חג'אג'רה": "north",
  "טמרה בגלבוע": "north",
  "יזרעאל": "north",
  "יפיע": "north",
  "יפעת": "north",
  "כדורי": "north",
  "כפר ברוך": "north",
  "כפר גדעון": "north",
  "כפר החורש": "north",
  "כפר יהושע": "north",
  "כפר יחזקאל": "north",
  "כפר כנא": "north",
  "כפר מצר": "north",
  "כפר קיש": "north",
  "כפר תבור": "north",
  "כפר תקווה": "north",
  "מגדל העמק": "north",
  "מגן שאול": "north",
  "מוקיבלה": "north",
  "מזרע": "north",
  "מנשית זבדה": "north",
  "מרחביה מושב": "north",
  "מרחביה קיבוץ": "north",
  "משהד": "north",
  "נעורה": "north",
  "נהלל": "north",
  "נופית": "north",
  "נורית": "north",
  "נין": "north",
  "נצרת": "north",
  "נוף הגליל": "north",
  "נצרת עילית": "north",
  "סואעד חמירה": "north",
  "סולם": "north",
  "סנדלה": "north",
  "עדי": "north",
  "עילוט": "north",
  "עין דור": "north",
  "עין חרוד": "north",
  "עין מאהל": "north",
  "עפולה": "north",
  "ציפורי": "north",
  "קריית טבעון-בית זייד": "north",
  "ראס עלי": "north",
  "ריינה": "north",
  "רם און": "north",
  "רמת דוד": "north",
  "רמת ישי": "north",
  "רמת צבי": "north",
  "שבלי": "north",
  "שדה יעקב": "north",
  "שדמות דבורה": "north",
  "שמשית": "north",
  "שער העמקים": "north",
  "שריד": "north",
  "תל יוסף": "north",
  "תל עדשים": "north",
  "תמרת": "north",

  // === NORTH - ואדי ערה (Wadi Ara) ===
  "אום אל פחם": "north",
  "באקה אל גרבייה": "north",
  "ברטעה": "north",
  "ג'ת": "north",
  "גבעת עוז": "north",
  "גלעד": "north",
  "דליה": "north",
  "חריש": "north",
  "יקנעם המושבה והזורע": "north",
  "יקנעם עילית": "north",
  "יוקנעם": "north",
  "כפר קרע": "north",
  "קיבוץ מגידו": "north",
  "מגל": "north",
  "מדרך עוז": "north",
  "מועאוויה": "north",
  "מי עמי": "north",
  "מייסר": "north",
  "מעלה עירון": "north",
  "משמר העמק": "north",
  "עין השופט": "north",
  "ערערה": "north",
  "קציר": "north",
  "רגבים": "north",
  "רמות מנשה": "north",
  "רמת השופט": "north",

  // === NORTH - בקעת בית שאן (Beit She'an Valley) ===
  "בית אלפא וחפציבה": "north",
  "בית השיטה": "north",
  "בית יוסף": "north",
  "בית שאן": "north",
  "גשר": "north",
  "חוות עדן": "north",
  "חמדיה": "north",
  "טייבה בגלבוע": "north",
  "טירת צבי": "north",
  "ירדנה": "north",
  "כפר רופין": "north",
  "מולדת": "north",
  "מירב": "north",
  "מנחמיה": "north",
  "מסילות": "north",
  "מעוז חיים": "north",
  "מעלה גלבוע": "north",
  "נווה אור": "north",
  "נוה איתן": "north",
  "ניר דוד": "north",
  "עין הנצי''ב": "north",
  "רוויה": "north",
  "רחוב": "north",
  "רשפים": "north",
  "שדה אליהו": "north",
  "שדה נחום": "north",
  "שדי תרומות": "north",
  "שלוחות": "north",
  "תל תאומים": "north",
  "מעלה אפרים": "north",

  // === HAIFA - המפרץ (Haifa Bay) ===
  "חיפה": "haifa",
  "חיפה - כרמל ועיר תחתית": "haifa",
  "חיפה - מערב": "haifa",
  "חיפה - נווה שאנן ורמות כרמל": "haifa",
  "חיפה - קריית חיים ושמואל": "haifa",
  "חיפה-מפרץ": "haifa",
  "טירת כרמל": "haifa",
  "יגור": "haifa",
  "כפר ביאליק": "haifa",
  "כפר גלים": "haifa",
  "כפר המכבי": "haifa",
  "כפר חסידים": "haifa",
  "נשר": "haifa",
  "קריית ביאליק": "haifa",
  "קריית ים": "haifa",
  "קריית מוצקין": "haifa",
  "קריית אתא": "haifa",
  "רכסים": "haifa",
  "רמת יוחנן": "haifa",

  // === HAIFA - הכרמל (Carmel) ===
  "בית אורן": "haifa",
  "דור": "haifa",
  "דלית אל כרמל": "haifa",
  "הבונים": "haifa",
  "עין הוד": "haifa",
  "עין חוד": "haifa",
  "עספיא": "haifa",
  "עתלית": "haifa",
  "פוריידיס": "haifa",
  "נחשולים": "haifa",
  "עופר": "haifa",

  // === HAIFA - מנשה (Hadera area) ===
  "אור עקיבא": "haifa",
  "בנימינה": "haifa",
  "ברקאי": "haifa",
  "ג'סר א-זרקא": "haifa",
  "גבעת עדה": "haifa",
  "גן השומרון": "haifa",
  "גן שמואל": "haifa",
  "זכרון יעקב": "haifa",
  "חדרה": "haifa",
  "חדרה - מזרח": "haifa",
  "חדרה - מערב": "haifa",
  "חדרה - מרכז": "haifa",
  "כפר פינס": "haifa",
  "מעגן מיכאל": "haifa",
  "מעיין צבי": "haifa",
  "מענית": "haifa",
  "משמרות": "haifa",
  "עין עירון": "haifa",
  "עין שמר": "haifa",
  "פרדס חנה-כרכור": "haifa",
  "קיסריה": "haifa",
  "שדות ים": "haifa",

  // === SHARON (שרון) ===
  "אביחיל": "sharon",
  "אבן יהודה": "sharon",
  "אודים": "sharon",
  "אורנית": "sharon",
  "אלפי מנשה": "sharon",
  "אלקנה": "sharon",
  "בית יצחק - שער חפר": "sharon",
  "בני דרור": "sharon",
  "ג'לג'וליה": "sharon",
  "גבעת חיים איחוד": "sharon",
  "גבעת חיים מאוחד": "sharon",
  "גבעת חן": "sharon",
  "געש": "sharon",
  "הוד השרון": "sharon",
  "חבצלת השרון וצוקי ים": "sharon",
  "טייבה": "sharon",
  "טירה": "sharon",
  "כוכב יאיר - צור יגאל": "sharon",
  "כפר הס": "sharon",
  "כפר ויתקין": "sharon",
  "כפר חיים": "sharon",
  "כפר יונה": "sharon",
  "כפר מונש": "sharon",
  "כפר מל''ל": "sharon",
  "כפר נטר": "sharon",
  "כפר סבא": "sharon",
  "כפר קאסם": "sharon",
  "מכמורת": "sharon",
  "מעברות": "sharon",
  "משמר השרון": "sharon",
  "משמרת": "sharon",
  "מתן": "sharon",
  "נורדיה": "sharon",
  "ניצני עוז": "sharon",
  "ניר אליהו": "sharon",
  "נירית": "sharon",
  "נתניה": "sharon",
  "נתניה - מזרח": "sharon",
  "נתניה - מערב": "sharon",
  "עין החורש": "sharon",
  "פרדסיה": "sharon",
  "צופים": "sharon",
  "צופית": "sharon",
  "צור יצחק": "sharon",
  "צור משה": "sharon",
  "קדימה-צורן": "sharon",
  "קלנסווה": "sharon",
  "רמת השרון": "sharon",
  "רעננה": "sharon",
  "רשפון": "sharon",
  "שער אפרים": "sharon",
  "שערי תקווה": "sharon",
  "שפיים": "sharon",
  "תל מונד": "sharon",

  // === DAN (דן) - Tel Aviv Metro ===
  "אור יהודה": "dan",
  "אזור": "dan",
  "בני ברק": "dan",
  "בת-ים": "dan",
  "בת ים": "dan",
  "גבעת שמואל": "dan",
  "גבעתיים": "dan",
  "גני תקווה": "dan",
  "הרצליה": "dan",
  "הרצליה - מערב": "dan",
  "הרצליה - מרכז וגליל ים": "dan",
  "חולון": "dan",
  "יהוד-מונוסון": "dan",
  "כפר שמריהו": "dan",
  "סביון": "dan",
  "פתח תקווה": "dan",
  "קריית אונו": "dan",
  "רמת גן": "dan",
  "רמת גן - מזרח": "dan",
  "רמת גן - מערב": "dan",
  "תל אביב": "dan",
  "תל אביב - יפו": "dan",
  "תל אביב - דרום העיר ויפו": "dan",
  "תל אביב - מזרח": "dan",
  "תל אביב - מרכז העיר": "dan",
  "תל אביב - עבר הירקון": "dan",

  // === DAN - ירקון (Modi'in / Rosh HaAyin) ===
  "אלעד": "dan",
  "בארות יצחק": "dan",
  "חשמונאים": "dan",
  "כפר האורנים": "dan",
  "לפיד": "dan",
  "מבוא חורון": "dan",
  "מודיעין": "dan",
  "מודיעין עילית": "dan",
  "מודיעין-מכבים-רעות": "dan",
  "נחלים": "dan",
  "ראש העין": "dan",
  "שהם": "dan",
  "שוהם": "dan",
  "שילת": "dan",
  "שעלבים": "dan",

  // === DAN - השפלה (Lod/Ramle/Rehovot) ===
  "באר יעקב": "dan",
  "בית דגן": "dan",
  "גזר": "dan",
  "גן שורק": "dan",
  "לוד": "dan",
  "מזכרת בתיה": "dan",
  "נס ציונה": "dan",
  "נען": "dan",
  "קריית עקרון": "dan",
  "ראשון לציון": "dan",
  "ראשון לציון - מזרח": "dan",
  "ראשון לציון - מערב": "dan",
  "רחובות": "dan",
  "רמלה": "dan",

  // === JERUSALEM (ירושלים) ===
  "גבעת זאב": "jerusalem",
  "ירושלים": "jerusalem",
  "ירושלים - דרום": "jerusalem",
  "ירושלים - מזרח": "jerusalem",
  "ירושלים - מערב": "jerusalem",
  "ירושלים - מרכז": "jerusalem",
  "ירושלים - צפון": "jerusalem",
  "מבשרת ציון": "jerusalem",
  "מוצא עילית": "jerusalem",

  // === JERUSALEM - שפלת יהודה (Beit Shemesh area) ===
  "אבו גוש": "jerusalem",
  "אבו-גוש": "jerusalem",
  "בית שמש": "jerusalem",
  "בר גיורא": "jerusalem",
  "הר אדר": "jerusalem",
  "טל שחר": "jerusalem",
  "מעלה החמישה": "jerusalem",
  "נווה אילן": "jerusalem",
  "נווה שלום": "jerusalem",
  "נס הרים": "jerusalem",
  "צור הדסה": "jerusalem",
  "צרעה": "jerusalem",
  "קריית יערים": "jerusalem",
  "קריית ענבים": "jerusalem",

  // === JERUSALEM - יהודה ושומרון (West Bank) ===
  "אלון שבות": "jerusalem",
  "אפרת": "jerusalem",
  "אריאל": "jerusalem",
  "ביתר עילית": "jerusalem",
  "בית אל": "jerusalem",
  "בית אריה": "jerusalem",
  "גבע בנימין": "jerusalem",
  "כוכב יעקב": "jerusalem",
  "כפר אדומים": "jerusalem",
  "כפר עציון": "jerusalem",
  "מעלה אדומים": "jerusalem",
  "מצפה יריחו": "jerusalem",
  "נווה דניאל": "jerusalem",
  "עלי": "jerusalem",
  "עפרה": "jerusalem",
  "קדומים": "jerusalem",
  "קריית ארבע": "jerusalem",
  "קרני שומרון": "jerusalem",
  "חברון": "jerusalem",

  // === SOUTH (דרום) - Lachish / Ashkelon / Ashdod ===
  "אשדוד": "south",
  "אשדוד - א,ב,ד,ה": "south",
  "אשדוד - ג,ו,ז": "south",
  "אשדוד - ח,ט,י,יג,יד,טז": "south",
  "אשקלון": "south",
  "אשקלון - דרום": "south",
  "אשקלון - צפון": "south",
  "גדרה": "south",
  "גן יבנה": "south",
  "יבנה": "south",
  "כפר אחים": "south",
  "כרם ביבנה": "south",
  "קריית גת": "south",
  "קריית מלאכי": "south",
  "גבעת ברנר": "south",

  // === SOUTH - Negev (Beer Sheva area) ===
  "באר שבע": "south",
  "באר שבע - דרום": "south",
  "באר שבע - מזרח": "south",
  "באר שבע - מערב": "south",
  "באר שבע - צפון": "south",
  "דימונה": "south",
  "חורה": "south",
  "להבים": "south",
  "מיתר": "south",
  "עומר": "south",
  "ערד": "south",
  "רהט": "south",
  "שגב שלום": "south",
  "תל שבע": "south",

  // === SOUTH - West Negev ===
  "אופקים": "south",
  "נתיבות": "south",
  "ירוחם": "south",
  "מצפה רמון": "south",
  "שדה בוקר": "south",

  // === SOUTH - Eilat / Arava ===
  "אילת": "south",
  "אילות": "south",
  "יטבתה": "south",
  "באר אורה": "south",
  "לוטן": "south",
  "נאות סמדר": "south",
  "ספיר": "south",
  "עין יהב": "south",
  "פארן": "south",
  "צופר": "south",
  "קטורה": "south",
  "יהל": "south",

  // === GAZA ENVELOPE (עוטף עזה) ===
  "אבשלום": "gaza_envelope",
  "אור הנר": "gaza_envelope",
  "ארז": "gaza_envelope",
  "בארי": "gaza_envelope",
  "גברעם": "gaza_envelope",
  "זיקים": "gaza_envelope",
  "קיבוץ זיקים": "gaza_envelope",
  "חולית": "gaza_envelope",
  "יבול": "gaza_envelope",
  "יד מרדכי": "gaza_envelope",
  "יכיני": "gaza_envelope",
  "יתד": "gaza_envelope",
  "כיסופים": "gaza_envelope",
  "כפר מימון ותושיה": "gaza_envelope",
  "כפר עזה": "gaza_envelope",
  "כרם שלום": "gaza_envelope",
  "כרמיה": "gaza_envelope",
  "מפלסים": "gaza_envelope",
  "נחל עוז": "gaza_envelope",
  "ניר יצחק": "gaza_envelope",
  "ניר עוז": "gaza_envelope",
  "נירים": "gaza_envelope",
  "נתיב העשרה": "gaza_envelope",
  "סופה": "gaza_envelope",
  "סעד": "gaza_envelope",
  "עין הבשור": "gaza_envelope",
  "עין השלושה": "gaza_envelope",
  "עלומים": "gaza_envelope",
  "רעים": "gaza_envelope",
  "שדה אברהם": "gaza_envelope",
  "שדרות": "gaza_envelope",
  "שדרות, איבים, ניר עם": "gaza_envelope",
  "שלומית": "gaza_envelope",
  "תקומה": "gaza_envelope",
};

/**
 * Resolve a Hebrew city name to its macro-region.
 * Returns undefined if the city is not in the mapping.
 */
export function cityToRegion(city: string): Region | undefined {
  const trimmed = city.trim();
  return CITY_REGION_MAP[trimmed];
}

/**
 * Given a list of cities from an alert, returns deduplicated set of affected regions.
 */
export function citiesToRegions(cities: string[]): Region[] {
  const regions = new Set<Region>();
  for (const city of cities) {
    const region = cityToRegion(city);
    if (region) {
      regions.add(region);
    }
  }
  return [...regions];
}

/**
 * Best-effort region for an alert: returns the most common region among the cities.
 * If tied, returns the first in REGIONS order.
 */
export function primaryRegion(cities: string[]): Region | undefined {
  const counts = new Map<Region, number>();
  for (const city of cities) {
    const region = cityToRegion(city);
    if (region) {
      counts.set(region, (counts.get(region) ?? 0) + 1);
    }
  }

  if (counts.size === 0) return undefined;

  let best: Region | undefined;
  let bestCount = 0;
  for (const r of REGIONS) {
    const c = counts.get(r) ?? 0;
    if (c > bestCount) {
      best = r;
      bestCount = c;
    }
  }
  return best;
}
