name = "kazam-alert-proxy"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[placement]
mode = "smart"

[[kv_namespaces]]
binding = "ALERTS_CACHE"
id = "a187584d9d874a1ca7367d16427675e5"

[triggers]
crons = ["* * * * *"]
